=== Reddyho/xml-demo/ship.xsd
<?xml version = "1.0" encoding = "UTF-8"?>

<xsd:schema xmlns:xsd = "http://www.w3.org/2001/XMLSchema">

<xsd:element     name="shipOrder" type="order"/>

<xsd:complexType name="order">
   <xsd:sequence>
  <xsd:element   name="shipTo"    type="shipAddress"/>
  <xsd:element   name="items"     type="cdItems"/>
</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="shipAddress">
    <xsd:sequence>
  <xsd:element   name="name"      type="xsd:string"/>
  <xsd:element   name="street"    type="xsd:string"/>
  <xsd:element   name="address"   type="xsd:string"/>
  <xsd:element   name="state">
      <xsd:complexType>
          <xsd:choice>
              <xsd:element name="IndianState"></xsd:element>
              <xsd:element name="USState"></xsd:element>
          </xsd:choice>
      </xsd:complexType>
  </xsd:element>
  <xsd:element   name="country"   type="xsd:string"/>
</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="cdItems">
    <xsd:sequence>
  <xsd:element   name="item"      minOccurs="0" maxOccurs="unbounded" type="cdItem"/>
</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="cdItem">
<xsd:sequence>
  <xsd:element   name="title"     type="xsd:string"/>
  <xsd:element   name="quantity"  type="xsd:positiveInteger"/>
  <xsd:element   name="price"     type="xsd:decimal"/>
  <xsd:element   name="ddate"     type="xsd:date"/>
</xsd:sequence>
</xsd:complexType>

</xsd:schema>

=== Reddyho/xml-demo/shipping.xml
<?xml version="1.0" encoding="UTF-8"?>
<shipOrder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  
xsi:noNamespaceSchemaLocation="ship.xsd">

  <shipTo>
    <name>Tove Svendson</name>
    <street>Ragnhildvei 2</street>
    <address>4000 Stavanger</address>
    <state><USState>texes</USState></state>
    <country>US</country>
  </shipTo>
  <items>
    <item>
      <title>Empire Burlesque</title>
      <quantity>10</quantity>
      <price>55</price>
      <ddate>2021-06-25</ddate>
    </item>
    <item>
      <title>Hide your heart</title>
      <quantity>1</quantity>
      <price>9.90</price>
      <ddate>2021-06-25</ddate>
    </item>
  </items>
</shipOrder>
